### ISSUE TITLE
Use the new import swagger definiton feature

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/aws-swagger-import#10]
It seems that of today, it is possible to import your swagger definition directly into API Gateway. https://aws.amazon.com/about-aws/whats-new/2016/04/amazon-api-gateway-supports-swagger-definition-import

So I guess we should just throw away everything we have right now and make it a tool that actually calls the correct functions and let Amazon handle importing swagger definitions.

So basically, all the work done here is moot and can be tossed away...

What do you think @aceew ?

**Comment by SamVerschueren** [comment]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#putRestApi-property

**Comment by aceew** [comment]
Haha it seems I chose an unfortunate time to start contributing. I think updating this to be a helper for the new AWS SDK api gateway methods is probably best, yeah.

**Comment by SamVerschueren** [comment]
Actually not, I was able to keep a lot of the stuff. Your contribution as well :). It came right on time as I was implementing the entire update stuff yesterday evening myself. I saw the new feature right on time...

**Comment by SamVerschueren** [comment]
@aceew The [aws-swagger-cli](https://github.com/SamVerschueren/aws-swagger-cli) is updated as well to use this new feature. Importing, update etc. should work because it is all handled by Amazon now. Feedback more then welcome ;).
